### ISSUE TITLE
Last frame of video flashes before the video starts

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-video#201]
<b>How it works now:</b>
1. Using the WebM's in this Presentation, notice that there is a flash of the last frame of the webM before the video starts. 
2. It's difficult to see over Screenconnect, but you can see it in this video: https://photos.app.goo.gl/CrrI62wwMegO57Vy1

<b>How it should work:</b>
You should not see a flash of the last frame of the video when playing in a Presentation.

**Comment by jungeunyoon** [comment]
@robb-price Currently looking into this. I'll report back after investigating, thanks!

**Comment by rudibravo** [comment]
@robb-price I've a proposed fix for this issue, can you verify if the issue is really gone?

We've setup a presentation with two videos that was problematic before

https://apps.risevision.com/editor/workspace/ef751d9f-e4a3-458c-b499-55ceee9b7015/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

Thanks

**Comment by sheadarlison** [comment]
@robb-price if possible could you setup a test Presentation for the user they could add to their schedule and also confirm.

**Comment by rudibravo** [comment]
@robb-price fix is deployed to production. please verify.

**Comment by robb-price** [comment]
@rudibravo My Display looks good, so I am informing the user and closing this issue. Thanks!

**Comment by sheadarlison** [comment]
Issue is back open as we had to revert the fix which we believe caused https://github.com/Rise-Vision/widget-video/issues/203

**Comment by stulees** [comment]
We are closing the issue. To recap our attempted fixes:

- Rewind the video to the first frame when it pauses
  - This fixed the issue but caused multiple blank displays on several users. When we rewind the video it starts loading the video contents, but sometimes the request would be pending forever on Chrome. Since the request is pending the widget never calls done and the presentation is stuck at that point. This bug was much less visible on Chrome 56 (compared to 59). After the Chrome rollback we added additional logs and re-deployed the fix, but unfortunately we still got a blank screen and decided to rollback our changes.
  - https://github.com/Rise-Vision/widget-video/pull/202
  - https://github.com/Rise-Vision/widget-video/pull/206
- Hide the video while seeking
  - This solution creates a visible white blink which is not on par with the quality we want to deliver to users.
  - https://github.com/Rise-Vision/widget-video/pull/208

Further testing involved setting up simple HTML presentation with videos looping using only videojs and no Video widgets. This had positive results in both Preview (Chrome 66) and in Player (Linux). However, results still varied given on lower performing machines. Since this HTML presentation test runs with static content and no Viewer communication, there was no feasible solution to pull from it right now. 

The test mentioned above confirms that in the future, when Player is on a higher Chromium version (66+), Viewer is deprecated, and the display is running on a supported platform with solid performance specs, this should no longer be an issue.
